In [3]:
import pandas as pd

In [135]:
df = pd.read_excel(r"C:\Users\Steph\Desktop\All Python\Data Analysis\Data cleaning\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002.0,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003.0,Walter,/White,7066950392.0,298 Drugs Driveway,N,NaN,True
3,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005.0,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007.0,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008.0,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009.0,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011.0,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012.0,Harry,...Potter,7066950392.0,2394 Hogwarts Avenue,Y,NaN,True
12,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014.0,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017.0,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018.0,Clark,Kent,7066950392.0,3498 Super Lane,Y,NaN,True
18,1019.0,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020.0,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020.0,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [136]:
df = df.drop_duplicates()    #drop duplicates
df    #saves new dataframe

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002.0,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003.0,Walter,/White,7066950392.0,298 Drugs Driveway,N,NaN,True
3,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005.0,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007.0,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008.0,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009.0,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011.0,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012.0,Harry,...Potter,7066950392.0,2394 Hogwarts Avenue,Y,NaN,True
12,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014.0,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017.0,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018.0,Clark,Kent,7066950392.0,3498 Super Lane,Y,NaN,True
18,1019.0,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020.0,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [137]:
df = df.drop(columns = "Not_Useful_Column")    #drops a column, 'saves df' or 'inplace=True' is specified, it means that the operation will modify the original DataFrame itself
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002.0,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003.0,Walter,/White,7066950392.0,298 Drugs Driveway,N,NaN
3,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005.0,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007.0,Jeff,Winger,NaN,1209 South Street,No,No
7,1008.0,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009.0,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011.0,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012.0,Harry,...Potter,7066950392.0,2394 Hogwarts Avenue,Y,NaN
12,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014.0,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015.0,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017.0,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018.0,Clark,Kent,7066950392.0,3498 Super Lane,Y,NaN
18,1019.0,Creed,Braton,N/a,N/a,N/a,Yes
19,1020.0,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [138]:
#df["Last_Name"] = df["Last_Name"].str.strip("...")    #before = saves to the df["Last_Name"]
#df["Last_Name"] = df["Last_Name"].str.strip("/")      #after = strips character from column
#df["Last_Name"] = df["Last_Name"].str.strip("_")
df["Last_Name"] = df["Last_Name"].str.strip("123._/")   #You can put all characters together
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002.0,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003.0,Walter,White,7066950392.0,298 Drugs Driveway,N,NaN
3,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005.0,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007.0,Jeff,Winger,NaN,1209 South Street,No,No
7,1008.0,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009.0,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011.0,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012.0,Harry,Potter,7066950392.0,2394 Hogwarts Avenue,Y,NaN
12,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014.0,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015.0,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017.0,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018.0,Clark,Kent,7066950392.0,3498 Super Lane,Y,NaN
18,1019.0,Creed,Braton,N/a,N/a,N/a,Yes
19,1020.0,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [139]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002.0,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003.0,Walter,White,7066950392.0,298 Drugs Driveway,N,NaN
3,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005.0,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007.0,Jeff,Winger,NaN,1209 South Street,No,No
7,1008.0,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009.0,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011.0,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012.0,Harry,Potter,7066950392.0,2394 Hogwarts Avenue,Y,NaN
12,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014.0,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015.0,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017.0,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018.0,Clark,Kent,7066950392.0,3498 Super Lane,Y,NaN
18,1019.0,Creed,Braton,N/a,N/a,N/a,Yes
19,1020.0,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [147]:
#get rid of all non numeric data in column
#Change entire column to strings
#df ["Phone_Number"] = df ["Phone_Number"].str.replace("[^a-zA-Z0-9]", "")
#inside the bracket says replace all characters 'except these characters a-zA-Z0-9' and replace them with nothing
###df ["Phone_Number"].apply(lambda x: x[0:3] + "-" + x[3:6] + "-" + x[6:10])  #formats the 1st 3 strings then the next and the next. 
###Above gets error needs to be a string
#df ["Phone_Number"] = df ["Phone_Number"].apply(lambda x: str(x)) #applys lambda to each value of x making it a string
#df ["Phone_Number"] = df ["Phone_Number"].apply(lambda x: x[0:3] + "-" + x[3:6] + "-" + x[6:10])
#Above formats the string(number)
#df ["Phone_Number"] = df ["Phone_Number"].str.replace('nan--', '')
df ["Phone_Number"] = df ["Phone_Number"].str.replace('Na--', '')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002.0,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003.0,Walter,White,,298 Drugs Driveway,N,NaN
3,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007.0,Jeff,Winger,,1209 South Street,No,No
7,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009.0,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011.0,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012.0,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015.0,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017.0,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018.0,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019.0,Creed,Braton,,N/a,N/a,Yes
19,1020.0,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [148]:
df[["Street Address","State", "Zip_Code"]]=df["Address"].str.split(',',2,expand=True)
#Above is creating different columns. They are appended and do not replace Address
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002.0,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003.0,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007.0,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009.0,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011.0,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012.0,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013.0,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015.0,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017.0,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018.0,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019.0,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020.0,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [149]:
df["Paying Customer"] = df["Paying Customer"].str.replace('Yes', 'Y')
df["Paying Customer"] = df["Paying Customer"].str.replace('No', 'N')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes', 'Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No', 'N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002.0,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003.0,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007.0,Jeff,Winger,,1209 South Street,N,N,1209 South Street,None,None
7,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009.0,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011.0,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012.0,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013.0,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015.0,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017.0,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018.0,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019.0,Creed,Braton,,N/a,N/a,Y,N/a,None,None
19,1020.0,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [151]:
#df = df.replace('N/a','')
df = df.fillna('') #This fills all Nan(not a number) with a blank
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002.0,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,,
2,1003.0,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004.0,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006.0,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007.0,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009.0,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011.0,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012.0,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013.0,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015.0,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017.0,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018.0,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
18,1019.0,Creed,Braton,,,,Y,,,
19,1020.0,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [152]:
#remove all rows with Y in Do_Not_Contact column
for x in df.index:
    if df.loc[x, "Do_Not_Contact"] == 'Y':
          df.drop(x, inplace=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003.0,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007.0,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009.0,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011.0,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012.0,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013.0,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015.0,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017.0,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018.0,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
19,1020.0,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [153]:
#If the column has a blank get rid of it
for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
          df.drop(x, inplace=True)
df
#Another way to drop null values
#df.dropna(subset="Phone_Number"), inplace=True

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
4,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
7,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
9,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
12,1013.0,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015.0,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017.0,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
19,1020.0,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [154]:
#Reset the index
df.reset_index(drop=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code
0,1001.0,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1005.0,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
2,1008.0,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
3,1010.0,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
4,1013.0,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
5,1014.0,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
6,1015.0,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
7,1016.0,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
8,1017.0,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
9,1020.0,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,